# Dependencies
markdown:         kramdown
kramdown:
  syntax-highlighter:  rouge

# Permalinks
permalink: /:year/:month/:day/:title.html
# relative_permalinks: true

# Setup
title:            R
tagline:          
description:      'Content for MIE 1402 tutorials'
baseurl: "/R-Tutorials-1" # If you are making a gh-pages project blog, this is
                        # the name of your project repo, preceded by a /'
                        # Set it to just "/" if you are making a user page.
                        
baseurlknitr:  "/R-Tutorials-1/" # This will always be your baseurl plus and extra '/'
                                # at the end.  It's used only when knitr renders
                                # your R Markdown files.
                        
url: "https://jennaleeb.github.io" # the base hostname & protocol for your site

# set limit on number of post to appear on Home page
homepostlimit: 10

# Disqus comments:
disqus:           true
shortname:        MIE1402

# Social Media
twitter:          false # add a twitter button to each post
facebook:         false # add a facebook share button to each post

author:
  name:           'Jenna Blumenthal'
  url:            jennaleeb.github.io

github:
  repo:           https://github.com/jennaleeb/R-Tutorials-1
